[package]
name = "seeding"
version = "0.0.2"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "postgres"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
toml = "0.7"
